### ISSUE TITLE
Create `mesop` CLI to support Bazel-agnostic hot reload

### ISSUE THREAD

**Issue by wwwillchen** [google/mesop#60]
After supporting `pip install mesop` (#41), one of the issues with running Mesop on pip is that it doesn't support hot reload. Right now, Mesop's [hot reload mechanism](https://google.github.io/mesop/internal/hot_reload/) relies on ibazel which injects the livereload script and sends a rebuild event.

# Questions:

- **How do we trigger a rebuild?** Whenever an app file changes. This isn't going to be as good as ibazel where there's a proper dependency graph. We will do a simple heuristic if any file within a directory or sub-directory of the main module is changed, then we will reload everything. This is the same heuristic used inside https://github.com/google/mesop/blob/541dcd4116e7f9250279d6084081eecf21962efc/mesop/cli/execute_module.py#L44
- **How do we send an event?** Ideally, we will use websockets, otherwise we can do some sort of polling on the client-side.

# Tasks:

- [x] Create a new CLI module (?) which supports `mesop run foo.py`
- [x] Make sure pip package points to CLI module (probably modify [setup.py](https://github.com/google/mesop/blob/541dcd4116e7f9250279d6084081eecf21962efc/mesop/pip_package/setup.py#L46))
- [x] Create a new build event communication channel from server to client (e.g. websocket or polling)
- [x] Update https://github.com/google/mesop/blob/main/mesop/web/src/services/hot_reload_watcher.ts to support both ibazel and CLI mode

# Prior Art

## Streamlit

- https://github.com/streamlit/streamlit/blob/develop/lib/streamlit/watcher/__init__.py
- Uses [Watchdog](https://github.com/gorakhargosh/watchdog)

## Gradio

- https://github.com/gradio-app/gradio/blob/main/gradio/cli/commands/reload.py
- Doesn't seem to be heavily relying on third-party python modules

## Home-grown

Basically create a while loop which checks file modified time.

```py
    last_modified = os.path.getmtime(module_path)
    while True:
        # Get the current modification time
        current_modified = os.path.getmtime(module_path)

        # Compare the current modification time with the last modification time
        if current_modified != last_modified:
            # Update the last modification time
            last_modified = current_modified
            module = read_module(module_path)
            if module is not None:
                try:
                    runtime.set_module(module)
                    runtime.reload_all_sessions()
                except Exception as e:
                    runtime.log(
                        pb.ServerLog(
                            message=f"Hot reload error: Module '{module_path}' has {e}.\n${traceback.format_exc()}",
                            level=pb.ServerLog.ERROR,
                        )
                    )

        # Wait for 1 second before checking again
        await asyncio.sleep(1)
```
